### ISSUE TITLE
Suggestion: find a way to inform the users that the project is not dead

### ISSUE THREAD

**Issue by leinardi** [Mcat12/shaku#12]
If there are no updates for long period of time (e.g. several months), you should find a way to let the user know that the project is not dead.

Can be something very simple like updating the README.md file every time that there is a new Rust release, stating that shaku is compatible with that release:

> ## Minimum Supported Rust Version
> Shaku supports the latest stable release of Rust (1.47.0), plus the previous two versions
> at minimum (but possibly more). Changes to the minimum supported version will be
> noted in the changelog.
> 
> Minimum supported version: 1.38.0

I just added the " (1.47.0)" after "latest stable release of Rust". It's just an excuse to make a new commit and show that the project is still active.

**Comment by Mcat12** [comment]
I can add a "Project Status" section to the readme. It would explain how I'm still active in the project but do not have many major features of my own planned for the future. Instead, I'd like to mature the library based on user feedback.

It's worth noting that Rust takes backwards-compatibility very seriously. You can run code written for Rust 1.0 on the most recent release with no issues. Backwards-incompatible changes are only made to fix bugs, for example bugs which break memory safety. There is also the editions system (https://doc.rust-lang.org/edition-guide/) which allows some more kinds of changes, but that is opt-in and backwards-compatible (libraries using Rust 2015 and Rust 2018 work together seamlessly).

Rust's backwards-compatibility means that it's not that important to signal that a library is compatible with the latest version of the language (especially compared to languages like JavaScript). That's why I'm a little hesitant to make this a big deal. The minimum compatible version of Rust is far more important, and already has a section of the readme dedicated to it.

**Comment by Mcat12** [comment]
Closed by https://github.com/Mcat12/shaku/commit/71ee7127d0ded2b58261ba2c1048fd4788711663
