### ISSUE TITLE
`shaku_actix` is not published to crates.io

### ISSUE THREAD

**Issue by ibraheemdev** [Mcat12/shaku#18]
`shaku_actix` is not published to crates.io.

**Comment by Mcat12** [comment]
Yep, I wrote it after the last release. Even though the next release is a major version change (breaking change), I expect `shaku_actix` to be compatible with both the current and next major versions. I'm not 100% sure though, which is why I've held off of publishing it, but I can publish a `0.1.0` without the cross-version compatibility.

**Comment by Mcat12** [comment]
[`shaku_actix`](https://crates.io/crates/shaku_actix) is now published!
