### ISSUE TITLE
Feature request: Lazy initialization

### ISSUE THREAD

**Issue by leinardi** [Mcat12/shaku#7]
I think it would be nice to create an instance of a component only the first time is actually requested at runtime, to avoid to generate all the instances at the same time and to keep everything in memory, even if won't be actually used at runtime.

Just to clarify with an example, I think would be nice if the instance of `DateLogger` trait will be create only when I call `module.resolve_ref()` and not when I call `MyModule::builder().build()`:

```
    let module = MyModule::builder()
        .with_component_parameters::<DateLoggerImpl>(DateLoggerImplParameters {
            today: "Jan 26".to_string(),
            year: 2020
        })
        .build();

    let date_logger: &dyn DateLogger = module.resolve_ref();
    date_logger.log_date();
```

**Comment by Mcat12** [comment]
Thinking through what it would take to implement this... I think I initially thought it would be easy, but there's complications. Notably the built module will be heavier-weight and there will be no more `resolve_mut`.

(thinking out loud, mostly about implementation details)

`resolve_ref` takes `&self` of the module and is currently just an `Arc::as_ref` call. With lazy components, the module would need to mutate itself so it can store the newly created component. Since modules are thread-safe, that means we would need to store the component in a thread-safe container, like `Mutex<Option<Arc<dyn MyComponentInterface>>>`. The `Option` is there because initially the component has not been created, since it's lazy.

Next we need to handle building the component after the module has been built. Building a component requires a mutable `ModuleBuildContext`, which usually is only live during module creation. Now it has to live alongside the module it builds, so there's some internal changes that have to happen, notably another mutex in the module (hopefully there's no deadlock situation). It will also increase the runtime of the module a bit.

Since the `ModuleBuildContext` now lives alongside the module, there will be at least two `Arc` references to each component. Since `resolve_mut` under the hood is `Arc::get_mut`, and that requires that only one reference exists, it will never successfully return a mutable reference to the component. That API will have to be removed.

Overall I think this change is doable, if a little more complicated that I originally imagined.

**Comment by Mcat12** [comment]
I've got an MVP of lazy components in the [`feat/lazy-components`] branch. To make a component lazy, add `#[lazy]` before the type in the module declaration:
```rust
module! {
    MyModule {
        components = [#[lazy] ServiceImpl],
        providers = []
    }
}
```

Note that even if a component is lazy, if it's a dependency of a non-lazy component it will still be created upfront.

There are some backwards-incompatible changes, including the removal of `resolve_mut`, added restrictions of `Send + Sync` for component parameters (when the `thread_safe` feature is on), and a slight change to `Module::build` (now it gets ownership of the build context instead of a mutable reference). Additionally, [`once_cell`] is added as a dependency to support to lazy component implementation.

Let me know what you think of this implementation!

[`feat/lazy-components`]: https://github.com/Mcat12/shaku/tree/feat/lazy-components
[`once_cell`]: https://crates.io/crates/once_cell

**Comment by leinardi** [comment]
Hey I think it looks good :) Currently I can test it but from what I saw I think OK! The only thing is loosing the `resolve_mut`, do you think this could not be worth the lazy feature?

**Comment by Mcat12** [comment]
I think it's OK to remove `resolve_mut`. I mentioned in https://github.com/Mcat12/shaku/issues/15#issuecomment-744035974 how it's hard to use correctly, and might even be an anti-pattern (needing to have a `&mut` reference to the module encourages you to wrap it in a `Mutex`).

**Comment by Mcat12** [comment]
Closed by https://github.com/Mcat12/shaku/commit/92b83b0e0ae501981b6c556a42e323eae2d1c29e
